"""Initial Migration

Revision ID: e55be3ba71d7
Revises: a11504ca56a8
Create Date: 2018-09-09 15:08:15.901810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55be3ba71d7'
down_revision = 'a11504ca56a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('username', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('votes', sa.Integer(), nullable=True))
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('categories', 'votes')
    op.drop_column('categories', 'username')
    # ### end Alembic commands ###
